# Generated by Django 3.2.20 on 2025-02-13 19:29

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('external_apply_link', models.URLField()),
                ('job_type', djongo.models.fields.JSONField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('posting_date', models.DateTimeField()),
            ],
        ),
    ]
